### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by deskinsjt** [cwru-pat/coffee_voting_system#35]
paper #id=41200

Look at the title and how the edit functionality deals with the "<" and ">".... what?

Edit: for reference, this refers to these pages:
http://glamdring.case.edu/coffee/add?post-id=41200
http://glamdring.case.edu/coffee/post.php?post-id=41200

**Comment by jbmertens** [comment]
The edit functionality (on the add page) relies on the summernote editor. The interaction between summernote and the html content seems to be the issue here; summernote is converting `$&lt;X_{max}&gt;$` to `$<X_{max}>$`, then treating this as an html tag and not rendering it. The actual content is still visible if you click the "code view" button in summernote. There may be a setting somewhere to ensure summernote interprets things correctly.

The title information is likely missing because we call strip_tags, and the title is interpreted as an html tag: https://github.com/cwru-pat/coffee_voting_system/blob/master/cron.php#L76

I'm not too inclined to fix these, but feel free :)
